# These are supported funding model platforms

custom: # Replace with up to 4 custom sponsorship URLs e.g., ['Kingmarti.manyvids.com', 'chaturbate.com/kingmarti','onlyfans.com/kingmarti','justfor.fans/kingmarticam]
